### ISSUE TITLE
Fix for pip installation errors in externally-managed environments and running Go-installed tools globally

### ISSUE THREAD

**Issue by Nixon-H** [hackersthan/anveshan#3]
When using Python in an externally-managed environment, users often encounter the following error when running `pip install`:

```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install python3-xyz, where xyz is the package you are trying to install.
```

### Solution:

1. **Resolve the Externally Managed Environment Error:**

   This error is caused by the restrictions imposed by the PEP 668 specification in newer Python versions. To avoid these pip errors, consider adding the following commands at the start of the code to remove the "EXTERNALLY-MANAGED" files for Python versions that are installed on the system:

   ```bash
   sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED
   sudo rm /usr/lib/python3.11/EXTERNALLY-MANAGED.original
   sudo rm /usr/lib/python3.12/EXTERNALLY-MANAGED
   sudo rm /usr/lib/python3.12/EXTERNALLY-MANAGED.original
   sudo rm /usr/lib/python3.13/EXTERNALLY-MANAGED
   sudo rm /usr/lib/python3.13/EXTERNALLY-MANAGED.original
   ```

   This step should be done based on the Python version being used. For systems with multiple Python versions, you can remove the "EXTERNALLY-MANAGED" files for all versions at once to avoid potential conflicts.

2. **Ensure Go-installed Tools Run from Anywhere:**

   After installing Go tools (such as `httpx`, `nuclei`, `katana`), they often fail to run due to missing paths in the terminal. To fix this, ensure that the Go bin path is added to the user's PATH, and the shell configuration file is sourced automatically.

   You can add the following checks and commands in the setup script to ensure the tools are accessible globally:

   ```bash
   # Add PATH and alias to the appropriate shell configuration file
   if [ -f "$HOME/.zshrc" ]; then
       CONFIG_FILE="$HOME/.zshrc"
   elif [ -f "$HOME/.bashrc" ]; then
       CONFIG_FILE="$HOME/.bashrc"
   else
       echo "No supported shell configuration file found."
       exit 1
   fi

   # Append commands to the appropriate configuration file
   echo 'export PATH="$PATH:$HOME/.local/bin"' >> "$CONFIG_FILE"
   echo 'alias httpx="$HOME/go/bin/httpx"' >> "$CONFIG_FILE"
   echo 'alias nuclei="$HOME/go/bin/nuclei"' >> "$CONFIG_FILE"
   echo 'alias katana="$HOME/go/bin/katana"' >> "$CONFIG_FILE"

   # Source the appropriate configuration file
   source "$CONFIG_FILE"

   # Check if the tools are working after installation
   httpx -up
   nuclei -up
   katana -up
   ```

   This solution ensures that Go tools such as `httpx`, `nuclei`, and `katana` can be run from anywhere in the terminal. This will provide smoother operation after installation, eliminating the need to use the full path (`$HOME/go/bin/httpx`) to run the tools.

**Comment by hackersthan** [comment]
Fix all of these issues and add some additional functionalities.

Errors
1. pip package installation error
2. `urlllib3` and `six` packages error
3. amass config error
4. httpx running from apt by default

Additional
1. Setup `GOPATH` if not exist. 
2. Confirmation before removing and installing `urllib3` and `six` packages.

**Comment by hackersthan** [comment]
Thank You for using `anveshan` in your recon process.

And special thanks to detect these problems and errors, I fixed all of them. I suggest you to completely remove anveshan tool from your system and reinstall it.

Thank You,
Sachin

**Comment by Nixon-H** [comment]
Please add `source "$CONFIG_FILE"` after the installation of the tools to ensure that the tools can be run from anywhere, and not in the start of the code.

**Comment by Nixon-H** [comment]
> Thank You for using `anveshan` in your recon process.
> 
> And special thanks to detect these problems and errors, I fixed all of them. I suggest you to completely remove anveshan tool from your system and reinstall it.
> 
> Thank You, Sachin

**It is my honor, brother.**

**Comment by Nixon-H** [comment]
**Another suggestion I want to put forth is to please consider adding the following code in your instructions:**

```bash
sudo apt install python3-venv python3-pip
python3.12 -m venv Nixon-V  # Adjust depending on the Python version (3.11 or 3.12)
source Nixon-V/bin/activate
```

*Note: The Python version varies; some Kali setups use Python 3.11, while others use Python 3.12 (observed during testing your tool in virtual machine Kali).*

After successfully installing all tools, deactivate the virtual environment manually using:

```bash
deactivate
```

**This way, errors will be prevented, and pip or Kali corruption (which sometimes breaks pip irreparably) will not occur.**

**Comment by hackersthan** [comment]
> Please add `source "$CONFIG_FILE"` after the installation of the tools to ensure that the tools can be run from anywhere, and not in the start of the code.

can you explain, do you want to run this tool from anywhere?
If yes you can do this by running
```bash
cp anveshan.sh /usr/local/bin
```

---

> Another suggestion I want to put forth is to please consider adding the following code in your instructions:

Yes i thought to use python environment variables, will think about it.


> Note: The Python version varies; some Kali setups use Python 3.11, while others use Python 3.12 (observed during testing your tool in virtual machine Kali).

I think python3.x version does not put any impact, because all of the tool support python3.x
There was a problem from pip3 `--break-system-package` that was fixed already.

If you found any error during running `bash anveshan.sh` please reply here.


Thank You,
Sachin

**Comment by Nixon-H** [comment]
> can you explain, do you want to run this tool from anywhere?

No. For the tools we are installing via `setup_linux.sh` using Go, such as Katana and HTTP, I asked you to add the Go binary path and `source ~/.bashrc` or `source ~/.zshrc` in the code after determining which shell the user is using, following the installation of the tools and before checking if the tools are working with your command, for example, `httpx -up`. This ensures that the tools can be run from anywhere, rather than having to specify `$HOME/go/bin/httpx`. (I noticed that `httpx` had to be run from the Go location yesterday after installation.)

**Comment by Nixon-H** [comment]
> I think python3.x version does not put any impact, because all of the tool support python3.x
> There was a problem from pip3 `--break-system-package` that was fixed already.

You are misunderstanding. I regret not articulating my point with greater clarity.

The ``setup_linux.sh`` bash script encounters an issue where using `pip` with the current Python installation in `/usr/bin/python3.xx` requires the `--break-system-package` option, yet some `pip` packages still produce the same error. This occurs because the Python installation is marked as **externally managed**.

**Externally managed** indicates that the package manager (such as `apt` on Debian-based systems) maintains control over the Python installation to prevent conflicts between system-level packages and user-installed packages.

When a Python installation is marked as externally managed, it restricts direct modifications through package management systems like `pip`. This is why using `--break-system-package` becomes necessary, as it forces `pip` to override these restrictions; however, it can lead to potential issues with the system’s Python environment, as this corrupts the environment in many cases as my environment was corrupted.

By removing these externally managed files, you can regain control over the Python environment, allowing you to install and manage packages without the need for the `--break-system-package` flag.

**Comment by hackersthan** [comment]
Hello @Nixon-H 

I already added a function to check if `--break-system-package` is required or not, If yes the tool will automatically append ` --break-system-package` in each and every `pip3 install` command. And if not required it will not append.
Thus this error has no impact on the `anveshan`.

Thank You,
Sachin

**Comment by Nixon-H** [comment]
> I already added a function to check if `--break-system-package` is required or not, If yes the tool will automatically append ` --break-system-package` in each and every `pip3 install` command. And if not required it will not append. Thus this error has no impact on the `anveshan`.

I will be testing your tool again on the VM. I will send you error screenshots if I encounter any.

**Comment by hackersthan** [comment]
I will fix the pip packages error by adding pip environment.

**Comment by hackersthan** [comment]
Added `python environment` system 597fdac07a43f42000ae338b090dbbc8f5939aaf
Now all the packages should install with their compatible version.
